spring.application.name=stronaQr

server.port=${SERVER_PORT:8080}

spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://${PGHOST:localhost}:${PGPORT:5432}/${PGDATABASE:strona_qr}}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:${PGUSER:postgres}}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:${PGPASSWORD:postgres}}
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false

app.cors.allowed-origin=${APP_CORS_ALLOWED_ORIGIN:http://localhost:4200}
app.admin.password=${APP_ADMIN_PASSWORD:KSM3D-MS23F-%MA1@-KASL!-93MFD}
